package com.v2gogo.project.db.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import com.v2gogo.project.db.CacheInfo;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession
{

	private final DaoConfig cacheInfoDaoConfig;

	private final CacheInfoDao cacheInfoDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap)
	{
		super(db);

		cacheInfoDaoConfig = daoConfigMap.get(CacheInfoDao.class).clone();
		cacheInfoDaoConfig.initIdentityScope(type);

		cacheInfoDao = new CacheInfoDao(cacheInfoDaoConfig, this);

		registerDao(CacheInfo.class, cacheInfoDao);
	}

	public void clear()
	{
		cacheInfoDaoConfig.getIdentityScope().clear();
	}

	public CacheInfoDao getCacheInfoDao()
	{
		return cacheInfoDao;
	}

}
