package com.v2gogo.project.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CacheData.
 */
public class CacheInfo implements java.io.Serializable
{
	private static final long serialVersionUID = 9001488941443851370L;
	public static final int TYPE_WELCOME = 0;
	public static final int TYPE_HOME = 1;
	public static final int TYPE_EXCHANGE = 2;
	public static final int TYPE_PEOPLE_CONCERN = 3;
	public static final int TYPE_V2GOGO_REAL_INTERACTION = 4;
	public static final int TYPE_SHOP = 5;
	public static final int TYPE_HOME_SUBJECT = 6;// 专题

	private Long id;
	private Integer type;
	private String response;

	public CacheInfo()
	{
	}

	public CacheInfo(Long id)
	{
		this.id = id;
	}

	public CacheInfo(Long id, Integer type, String response)
	{
		this.id = id;
		this.type = type;
		this.response = response;
	}

	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Integer getType()
	{
		return type;
	}

	public void setType(Integer type)
	{
		this.type = type;
	}

	public String getResponse()
	{
		return response;
	}

	public void setResponse(String response)
	{
		this.response = response;
	}

}
