package com.v2gogo.project.db;

import com.google.gson.annotations.SerializedName;
import com.v2gogo.project.utils.common.LogUtil;
import com.v2gogo.project.utils.qiniu.VersionPhotoUrlBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Master.
 */
public class MatserInfo implements java.io.Serializable
{

	private static final long serialVersionUID = 8596746968138243300L;

	@SerializedName("id")
	private String userid;

	private Integer vip;
	private Integer sex;
	private Integer coin;
	private Integer status;
	private Integer banned;
	private Integer allcoin;
	private Integer weekcoin;
	private Integer issignin;
	private Integer iscomment;

	private String city;
	private String username;
	private String img;
	private String devicetoken;
	private String invcode;
	private String fullname;
	private String userpass;
	private String token;
	private String phone;
	private String email;

	@SerializedName("lastlogintime")
	private long loginTime;

	public String getCity()
	{
		return city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getUsername()
	{
		return username;
	}

	public void setUsername(String username)
	{
		this.username = username;
	}

	public String getImg()
	{
		return VersionPhotoUrlBuilder.createVersionImageUrl(img);
	}

	public void setImg(String img)
	{
		this.img = img;
	}

	public String getUserid()
	{
		return userid;
	}

	public void setUserid(String userid)
	{
		this.userid = userid;
	}

	public Integer getVip()
	{
		return vip;
	}

	public void setVip(Integer vip)
	{
		this.vip = vip;
	}

	public Integer getSex()
	{
		return sex;
	}

	public void setSex(Integer sex)
	{
		this.sex = sex;
	}

	public Integer getCoin()
	{
		return coin;
	}

	public void setCoin(Integer coin)
	{
		this.coin = coin;
	}

	public Integer getStatus()
	{
		return status;
	}

	public void setStatus(Integer status)
	{
		this.status = status;
	}

	public Integer getBanned()
	{
		return banned;
	}

	public void setBanned(Integer banned)
	{
		this.banned = banned;
	}

	public Integer getAllcoin()
	{
		return allcoin;
	}

	public void setAllcoin(Integer allcoin)
	{
		this.allcoin = allcoin;
	}

	public Integer getWeekcoin()
	{
		return weekcoin;
	}

	public void setWeekcoin(Integer weekcoin)
	{
		this.weekcoin = weekcoin;
	}

	public Integer getIssignin()
	{
		return issignin;
	}

	public void setIssignin(Integer issignin)
	{
		this.issignin = issignin;
	}

	public Integer getIscomment()
	{
		return iscomment;
	}

	public void setIscomment(Integer iscomment)
	{
		this.iscomment = iscomment;
	}

	public String getDevicetoken()
	{
		return devicetoken;
	}

	public void setDevicetoken(String devicetoken)
	{
		this.devicetoken = devicetoken;
	}

	public String getInvcode()
	{
		return invcode;
	}

	public void setInvcode(String invcode)
	{
		this.invcode = invcode;
	}

	public String getFullname()
	{
		return fullname;
	}

	public void setFullname(String fullname)
	{
		this.fullname = fullname;
	}

	public String getUserpass()
	{
		return userpass;
	}

	public void setUserpass(String userpass)
	{
		this.userpass = userpass;
	}

	public String getToken()
	{
		return token;
	}

	public void setToken(String token)
	{
		this.token = token;
	}

	public String getPhone()
	{
		return phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public String getEmail()
	{
		return email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public long getLoginTime()
	{
		return loginTime;
	}

	public void setLoginTime(long loginTime)
	{
		this.loginTime = loginTime;
	}

	public String getThumbialAvatar()
	{
		return VersionPhotoUrlBuilder.createThumbialUserAvatar(getImg());
	}

	@Override
	public String toString()
	{
		return "MatserInfo [userid=" + userid + ", vip=" + vip + ", sex=" + sex + ", coin=" + coin + ", status=" + status + ", banned=" + banned + ", allcoin="
				+ allcoin + ", weekcoin=" + weekcoin + ", issignin=" + issignin + ", iscomment=" + iscomment + ", city=" + city + ", username=" + username
				+ ", img=" + img + ", devicetoken=" + devicetoken + ", invcode=" + invcode + ", fullname=" + fullname + ", userpass=" + userpass + ", token="
				+ token + ", phone=" + phone + ", email=" + email + ", loginTime=" + loginTime + "]";
	}
}
